#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# IsoCrates Production Deployment
#
# Generates secrets, configures Caddy HTTPS, and starts all services.
# Re-running is safe — existing .env.production values are preserved.
#
# Usage:
#   ./scripts/deploy.sh                     Interactive setup
#   DOMAIN=docs.example.com ./scripts/deploy.sh   Non-interactive (pre-set domain)
# =============================================================================

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env.production"

log()   { echo -e "${GREEN}[+]${NC} $*"; }
warn()  { echo -e "${YELLOW}[!]${NC} $*"; }
error() { echo -e "${RED}[x]${NC} $*" >&2; exit 1; }

# --- Prerequisites -----------------------------------------------------------

check_prereqs() {
    log "Checking prerequisites..."

    command -v docker >/dev/null 2>&1 \
        || error "Docker is required. Install: https://docs.docker.com/get-docker/"

    if docker compose version >/dev/null 2>&1; then
        COMPOSE="docker compose"
    elif command -v docker-compose >/dev/null 2>&1; then
        COMPOSE="docker-compose"
    else
        error "Docker Compose is required. Install: https://docs.docker.com/compose/install/"
    fi

    command -v openssl >/dev/null 2>&1 \
        || error "openssl is required for secret generation"

    log "Using: $COMPOSE"
}

# --- Secret Generation -------------------------------------------------------

generate_secret() {
    openssl rand -hex 32
}

# --- Interactive Setup --------------------------------------------------------

setup_env() {
    log "Configuring production environment..."

    # Domain
    if [ -z "${DOMAIN:-}" ]; then
        read -rp "$(echo -e "${BLUE}Enter your domain name (e.g. docs.example.com):${NC} ")" DOMAIN
        [ -z "$DOMAIN" ] && error "Domain is required for HTTPS"
    fi
    log "Domain: $DOMAIN"

    # Generate secrets if not already set
    if [ -z "${JWT_SECRET_KEY:-}" ]; then
        JWT_SECRET_KEY=$(generate_secret)
        log "Generated JWT_SECRET_KEY"
    fi

    if [ -z "${POSTGRES_PASSWORD:-}" ]; then
        POSTGRES_PASSWORD=$(generate_secret)
        log "Generated POSTGRES_PASSWORD"
    fi

    # Optional: GitHub webhook secret
    if [ -z "${GITHUB_WEBHOOK_SECRET:-}" ]; then
        read -rp "$(echo -e "${BLUE}GitHub Webhook Secret (Enter to skip):${NC} ")" GITHUB_WEBHOOK_SECRET
        GITHUB_WEBHOOK_SECRET="${GITHUB_WEBHOOK_SECRET:-}"
    fi

    # Write .env.production
    cat > "$ENV_FILE" <<EOF
# IsoCrates Production Configuration
# Generated by deploy.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# WARNING: Contains secrets. Do not commit to version control.

DOMAIN=${DOMAIN}
ENVIRONMENT=production

# Database
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql://isocrates:${POSTGRES_PASSWORD}@postgres:5432/isocrates

# Authentication
AUTH_ENABLED=true
JWT_SECRET_KEY=${JWT_SECRET_KEY}

# CORS
CORS_ALLOWED_ORIGINS=https://${DOMAIN}

# Webhooks
GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}

# Frontend
NEXT_PUBLIC_API_URL=https://${DOMAIN}
NEXT_PUBLIC_API_URL_INTERNAL=http://backend-api:8000

# Logging
LOG_LEVEL=INFO
LOG_FORMAT=json
EOF

    log "Wrote $ENV_FILE"

    # Ensure production files are gitignored
    for entry in ".env.production" "Caddyfile"; do
        if ! grep -qxF "$entry" "$SCRIPT_DIR/.gitignore" 2>/dev/null; then
            echo "$entry" >> "$SCRIPT_DIR/.gitignore"
            warn "Added $entry to .gitignore"
        fi
    done
}

# --- Caddyfile ----------------------------------------------------------------

write_caddyfile() {
    cat > "$SCRIPT_DIR/Caddyfile" <<EOF
${DOMAIN} {
    # API and health endpoints
    handle /api/* {
        reverse_proxy backend-api:8000
    }

    handle /health {
        reverse_proxy backend-api:8000
    }

    # Frontend (default)
    handle {
        reverse_proxy frontend:3001
    }
}
EOF
    log "Wrote Caddyfile for ${DOMAIN}"
}

# --- Deploy -------------------------------------------------------------------

deploy() {
    log "Starting production deployment..."

    cd "$SCRIPT_DIR"

    $COMPOSE \
        -f docker-compose.yml \
        -f docker-compose.prod.yml \
        --env-file "$ENV_FILE" \
        up -d --build

    echo ""
    log "Deployment complete!"
    echo ""
    echo -e "  ${GREEN}IsoCrates is running at:${NC} ${BLUE}https://${DOMAIN}${NC}"
    echo ""
    echo -e "  ${YELLOW}Next steps:${NC}"
    echo "  1. Ensure DNS for ${DOMAIN} points to this server's IP"
    echo "  2. Register the first user (auto-promoted to admin):"
    echo "     curl -X POST https://${DOMAIN}/api/auth/register \\"
    echo '       -H "Content-Type: application/json" \\'
    echo '       -d '"'"'{"display_name":"Admin","email":"admin@example.com","password":"..."}'"'"
    echo ""
    echo "  3. Health check: curl https://${DOMAIN}/health"
    echo "  4. View logs:    $COMPOSE -f docker-compose.yml -f docker-compose.prod.yml logs -f"
}

# --- Main ---------------------------------------------------------------------

main() {
    echo ""
    echo "  IsoCrates Production Deployment"
    echo "  ================================"
    echo ""

    check_prereqs

    # Load existing .env.production if present (for re-deploys)
    if [ -f "$ENV_FILE" ]; then
        warn "Found existing $ENV_FILE — reusing values"
        set -a; source "$ENV_FILE"; set +a
    fi

    setup_env
    write_caddyfile
    deploy
}

main "$@"
